name: Release disable_gc

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Verify version
        run: |
          PY_VER=$(python -c "import disable_gc;print(disable_gc.__version__)")
          echo Python version - "$PY_VER"
          SETUP_VER=$(awk "/version =/ { print \$3 }" setup.cfg)
          echo Setup.cfg version - "$SETUP_VER"
          [[ $PY_VER == $SETUP_VER ]]
          TAG_VER=$(echo ${{ github.event.release.tag_name }} | cut -c 2-)
          echo Tag version "$TAG_VER"
          [[ $TAG_VER == $PY_VER ]]
      - name: Build wheel
        run: pip wheel .
      - name: Install twine
        run: pip install twine
      - name: Publish on Test PyPi
        run: twine upload -r testpypi -u ${{ secrets.TEST_PYPI_USERNAME }} -p ${{ secrets.TEST_PYPI_PASSWORD }} disable_gc-*.whl
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'disable_gc-*.whl'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      

